env:
  es2021: true
  node: true
extends:
  - xo
  - prettier
overrides:
  - extends:
      - xo-typescript
      - prettier
    files:
      - '*.ts'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  {
    'prefer-template': error,
    '@typescript-eslint/no-confusing-void-expression':
      [error, { ignoreArrowShorthand: true, ignoreVoidOperator: true }],
    '@typescript-eslint/no-explicit-any': error,
  }
